# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

addons:
  postgresql: "9.3"

before_script:
  - psql -U postgres -c "create extension postgis;"

before_install:
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"
  - export CURWD=`pwd`
  - sudo apt-get install libproj-dev libgeos++-dev
  - cd
  - wget http://download.osgeo.org/gdal/2.1.0/gdal-2.1.0.tar.gz
  - tar zxf gdal-2.1.0.tar.gz
  - cd gdal-2.1.0
  - ./configure
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.3.tar.gz
  - tar zxvf proj-4.9.3.tar.gz
  - cd proj-4.9.3
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd $CURWD

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_binary_packages:
  - rgdal
  - sf

env:
  global:
    - NOT_CRAN=true
before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

notifications:
  email:
    on_success: change
    on_failure: change
