language: r
warnings_are_errors: true
sudo: required
# https://github.com/ropensci/rgbif/blob/master/.travis.yml#L9
dist: trusty

env:
  global:
    - NOT_CRAN=true
before_install:
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq

apt_packages:
  - udunits-bin
  - libudunits2-dev
  - libgdal-dev
  - libgdal1-dev
  - libproj-dev
  - libgeos++-dev

# We use clang, --without-libtool and --with-debug for faster build
compiler:
  - clang

r_binary_packages:
  - rgdal

notifications:
  email:
    on_success: change
    on_failure: change
