language: R
sudo: required

# https://github.com/ropensci/rgbif/blob/master/.travis.yml#L9
dist: trusty

addon:
  apt:
    packages:
      - libudunits2-dev

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libproj-dev libgeos++-dev libgdal-dev

# We use clang, --without-libtool and --with-debug for faster build
compiler:
  - clang


r_binary_packages:
  - rgdal

r_github_packages:
  - jimhester/covr

after_success:
  - R -e 'covr::codecov()'

env:
  global:
    - NOT_CRAN=true
before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

notifications:
  email:
    on_success: change
    on_failure: change
