language: r
dist: trusty
warnings_are_errors: true
sudo: required
apt-packages:
  - libudunits2-dev

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev libgdal-dev netcdf-bin gdal-bin

r_binary_packages:
  - rgdal

env:
  global:
    - NOT_CRAN=true
before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

notifications:
  email:
    on_success: change
    on_failure: change
